Effie ban patch 1
Orientalent/guidelines pull request #5
Opened 2022-01-24 10:12 UTC by EffieBan

2022-01-24 10:13 UTC, EffieBan commented
This is a mistake pull. Sorry.

2022-01-24 11:30 UTC, chuanjin requested changes

2022-01-24 11:30 UTC, chuanjin commented on blog/Arrival on Goteborg.md
> +___Full of passion and hope, we landed on Goteborg, Sweden. It almost took us 15 hours arriving here. There are many flights you can choose to take. The direct flight is the one from Beijing to Stock
7000RMB per person?

2022-01-24 11:34 UTC, chuanjin commented
Please put all photoes under **images** folder, and maybe you want to add mosaic for your kid.

2022-01-24 11:37 UTC, EffieBan commented
ok，wow, I think I need to learn it later. All things new to me. Haha

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: chuanjin ***@***.***>
Sent: Monday, January 24, 2022 12:34:43 PM
To: Orientalent/guidelines ***@***.***>
Cc: Effie ***@***.***>; Author ***@***.***>
Subject: Re: [Orientalent/guidelines] Effie ban patch 1 (PR #5)


Please put all photoes under images folder, and maybe you want to add mosaic for your kid.

—
Reply to this email directly, view it on GitHub<https://github.com/Orientalent/guidelines/pull/5#issuecomment-1020004301>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AXN3BNG4YHARJU3PMA5I7LDUXU2NHANCNFSM5MU5VDIQ>.
Triage notifications on the go with GitHub Mobile for iOS<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android<https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2022-01-26 13:57 UTC, chuanjin commented
- It is better to keep only one pull request and close the other one since they are the same.
- And remove the Effiesimages and keep the one inside **images** folder so that we only keep one copy.

2022-02-02 12:46 UTC, closed without merging